services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo_container_order
    restart: always
    env_file:
      - .env
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork
    logging:
      driver: "none"

  fast_api:
    container_name: orderPlacement
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8001:8000"
    networks:
      - mynetwork
    depends_on:
      - mongo

  redis-cache:
    image: redis:alpine
    container_name: redis-cache_order
    restart: on-failure
    ports:
      - '6380:6379'
    command: redis-server
    volumes:
      - cache:/data
    networks:
      - mynetwork

volumes:
  mongo_data:
  cache:

networks:
  mynetwork:
